server:
  port: 8081

proxy:
  upstream-base-url: https://httpbin.org
  connect-timeout-ms: 3000
  read-timeout-ms: 5000
  forward-headers:
    - Accept
    - User-Agent
    - Accept-Language

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics


spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s

logging:
  level:
    org.springframework.data.redis: INFO
    io.lettuce.core: INFO



